name: AWS OIDC Deployment

on:
  workflow_dispatch: 

# GITHUB_TOKEN necesita permisos para solicitar el JWT al proveedor de OIDC.
permissions:
  id-token: write   # Necesario para OIDC
  contents: read    # Necesario para hacer checkout del código

jobs:
  deploy-to-aws:
    environment: develop
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el código
        uses: actions/checkout@v4

      - name: Configurar Credenciales de AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ACTIONS_ROLE_ARN }} # Reemplaza con el ARN de tu rol
          aws-region: eu-north-1 # Reemplaza con tu región de AWS

      - name: Probar conexión a AWS
        run: |
          # Si esto funciona, significa que la autenticación OIDC fue exitosa
          aws sts get-caller-identity
          
      # A partir de aquí, añade tus pasos de despliegue (ej: aws s3 sync, docker push, etc.)
